nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

image:
  registry: "quay.io"
  repository: "pgrwl/pgrwl"
  tag: ""
  pullPolicy: IfNotPresent

pgconn:
  # If set, this secret will be used as the base PG env.
  # If empty, chart will create its own base secret from pgconn.values.
  existingSecret:
    enabled: false
    name: "pg-envs-secret"

  # Base values for secret when chart manages it
  values:
    PGHOST: "postgres"
    PGPORT: "5432"
    PGUSER: "postgres"
    PGPASSWORD: "postgres"

structuredConfig:
  main:
    listen_port: 7070
    directory: "/wals/wal-archive"
  receiver:
    slot: pgrwl_v5
    no_loop: true
    uploader:
      sync_interval: 10s
      max_concurrency: 4
  log:
    level: trace
    format: text
    add_source: true
  metrics:
    enable: true
  backup:
    cron: "0 0 * * *"
  retention:
    enable: true
    type: recovery_window
    value: 72h
    keep_last: 2
  storage:
    name: s3
    compression:
      algo: gzip
    encryption:
      algo: aes-256-gcm
      pass: qwerty123
    s3:
      url: https://minio:9000
      access_key_id: minioadmin
      secret_access_key: minioadmin123
      bucket: backups
      region: main
      use_path_style: true
      disable_ssl: true
  #   sftp:
  #     host: sftp.example.com
  #     port: 22
  #     user: backupuser
  #     pass: ""
  #     pkey_path: "/home/user/.ssh/id_rsa"
  #     pkey_pass: ""
  #     base_dir: "/mnt/wal-archive"

# required section
persistence:
  storageClassName: standard
  accessMode: ReadWriteOnce
  volumeMode: Filesystem
  size: 16Gi
service:
  type: ClusterIP
  port: 7070
args: ["daemon"]
env:
  PGRWL_DAEMON_MODE: "receive"
  PGRWL_CONFIG_PATH: "/etc/pgrwl/config.yml"

# optional section
livenessProbe: {}
readinessProbe: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
resources: {}
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
