---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pgrwl.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgrwl.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
